dist:
  bionic

os:
- linux
- osx
language: minimal

before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo snap install yq; fi
- brew install bats-core
- brew install shellcheck
- brew install yq

script: true